
create database Learn;
use Learn

--SQL COMMANDS


--CREATE

CREATE TABLE COUNTRIES(
COUNTRY_ID INT,
COUNTRY_CODE CHAR(2),
COUNTRY_NAME VARCHAR(20)
);

--INSERT

INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(1,'NE','NEPAL');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(2,'IN','INDIA');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(3,'CH','CHINA');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(4,'UK','UNITED KINGDOM');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(5,'US','AMERICA');

INSERT INTO COUNTRIES(COUNTRY_CODE,COUNTRY_ID,COUNTRY_NAME) VALUES('CA',6,'CANADA');

INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_NAME) VALUES(7,'AUSTRALIA');

INSERT INTO COUNTRIES(COUNTRY_CODE,COUNTRY_ID,COUNTRY_NAME) VALUES(NULL,8,'RUSSIA');

--SELECT

SELECT* FROM COUNTRIES;
SELECT* FROM COUNTRIES WHERE COUNTRY_ID=7;


--UPDATE

UPDATE COUNTRIES SET COUNTRY_CODE='AU' WHERE COUNTRY_ID=7;

--ALTER 

ALTER TABLE COUNTRIES ALTER COLUMN COUNTRY_CODE CHAR(3);

ALTER TABLE COUNTRIES ADD GDP DECIMAL(2,2);

--DELETE

DELETE FROM COUNTRIES WHERE COUNTRY_CODE= 'CA'; --DELETE ROW BY CONDITION 

--TRUNCATE

TRUNCATE TABLE COUNTRIES; --DELETE ALL ROWS FROM TABLE 

--DROP

DROP TABLE COUNTRIES; --DELETE TABLE FROM DATABASE AND ALL DATA

