
create database Learn;
use Learn

--SQL COMMANDS


--CREATE

CREATE TABLE COUNTRIES(
COUNTRY_ID INT,
COUNTRY_CODE CHAR(2),
COUNTRY_NAME VARCHAR(20)
);

--INSERT

INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(1,'NE','NEPAL');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(2,'IN','INDIA');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(3,'CH','CHINA');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(4,'UK','UNITED KINGDOM');
INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_CODE,COUNTRY_NAME) VALUES(5,'US','AMERICA');

INSERT INTO COUNTRIES(COUNTRY_CODE,COUNTRY_ID,COUNTRY_NAME) VALUES('CA',6,'CANADA');

INSERT INTO COUNTRIES(COUNTRY_ID,COUNTRY_NAME) VALUES(7,'AUSTRALIA');

INSERT INTO COUNTRIES(COUNTRY_CODE,COUNTRY_ID,COUNTRY_NAME) VALUES(NULL,8,'RUSSIA');

--SELECT

SELECT* FROM COUNTRIES;
